name: deploy to ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "[+] Cloning or pulling latest code..."
            if [ ! -d "TemplateEditor" ]; then
              git clone https://github.com/Aswin-AR5055/TemplateEditor.git TemplateEditor
            fi

            cd TemplateEditor
            git pull

            echo "[+] Stopping and removing existing container..."
            docker stop template || true
            docker rm template || true

            echo "[+] Removing existing Docker image..."
            docker rmi -f template || true

            echo "[+] Building Docker image..."
            docker build -t template .

            echo "[+] Running container..."
            docker run -d --name template -p 6000:6000 template

            echo "[+] Done! Current containers:"
            docker ps
